# HPs
BEAR_MAX_HP = 500
PLAYER_MAX_HP = 100
SWORD_DAMAGE_HP = 50
REDBULL_RECOVER_HP = 50
MIN_BEAR_DAMAGE_HP = 3
MAX_BEAR_DAMAGE_HP = 15

# Damage Ratio
HEAD_DAMAGE_COEF = 2
HEART_DAMAGE_COEF = 5
HAND_DAMAGE_COEF = 0.8
BODY_DAMAGE_COEF = 1.5

# Result Titles
PLAYER_WIN_TITLE = "YOU WIN!"
PLAYER_LOSE_TITLE = "GAME OVER!"